<a href="https://colab.research.google.com/github/Venni2911/LogicMojo-AI-ML-Sept25-VenniRaj/blob/main/Hints%20to%20solve%20-%20Credit_EDA_assignment_Approach.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Filtering out the warnings

import warnings

warnings.filterwarnings('ignore')

In [ ]:
# Importing the required libraries

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
# Read the csv file using 'read_csv'. Please write your dataset location here.

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/EDA Assignment - Logic Mojo Sep/application_data.csv')
df.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
df.shape

(307511, 122)

In [ ]:
df2 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/EDA Assignment - Logic Mojo Sep/previous_application.csv')
df2.head()

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,2030495,271877,Consumer loans,1730.430,17145.0,17145.0,0.0,17145.0,SATURDAY,15,...,Connectivity,12.0,middle,POS mobile with interest,365243.0,-42.0,300.0,-42.0,-37.0,0.0
1,2802425,108129,Cash loans,25188.615,607500.0,679671.0,NaN,607500.0,THURSDAY,11,...,XNA,36.0,low_action,Cash X-Sell: low,365243.0,-134.0,916.0,365243.0,365243.0,1.0
2,2523466,122040,Cash loans,15060.735,112500.0,136444.5,NaN,112500.0,TUESDAY,11,...,XNA,12.0,high,Cash X-Sell: high,365243.0,-271.0,59.0,365243.0,365243.0,1.0
3,2819243,176158,Cash loans,47041.335,450000.0,470790.0,NaN,450000.0,MONDAY,7,...,XNA,12.0,middle,Cash X-Sell: middle,365243.0,-482.0,-152.0,-182.0,-177.0,1.0
4,1784265,202054,Cash loans,31924.395,337500.0,404055.0,NaN,337500.0,THURSDAY,9,...,XNA,24.0,high,Cash Street: high,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df2.shape

(1670214, 37)

In [ ]:
### Find shape, Info & description of the data set

In [ ]:
### build understanding of the fields and use business sense to analyse which fileds are just noise 9 additional/ extra) and might not help in the analysis
### remove them if you feel it wont be useful

In [ ]:
### list down business questions which will help you analyse this data

In [ ]:
### Check the data for nulls and remove all columns with > 30/40% nulls

df.isnull().sum()/len(df) * 100

In [ ]:
#### IF data is missing for < 30% of the nulls values ->
### 1. Figure if that colums in necessary for analysis - Remove
### 2. See if imputation would make sense - > Replace the nulls using mean. median. mode .    [Try to impute using intraplation] [Advanced]

#### If a columns more 7-10% nulls, rather not impute -> manufacturing of data

### Replace?

### create box plots -> Outliers -> too many outliers -> Replace with median

df.loc[df.AMT_ANNUITY.isnull(), 'AMT_ANNUITY'] = median ()

In [ ]:
### study the values of columns for nulls - >
### there are few columns with values like NAN, NaN, XNA, XA -> Junk values ( filter these rows out if the junk values are more > 30% ) If it is less, see if you can impute

In [ ]:
## Check for gender, occuption type for junks

In [ ]:
#### outlier analysis


##Study if variables have outliers -> Box plot, IQR ( In for loop for multiple variables)

### study why there are outliers, does it makes sense or not
### For variables which do not make sense to have outliers, remove outliers using IQR - 90/10- or 95/5

In [ ]:
#### Univariate Analysis

### Pick one variable and understand the counts/ group by sums/ plot bar charts/ distributions  - Employee distrbution -> Salaried class are the most applicants in a loan setting

### Salaried class Employees are the ones with highest loan rejections


var_name. value_counts().plot.bar()

In [ ]:
### categorical variables

###Frequency charts - BoX

In [ ]:
### Some variables like Income, Credit History etc would be better to be analysed using bins - create 10/15 bins for this
l = ['2-100','101-200']
bins = [0,100,200]
pd.cut(df.var_name, bins, labels = l)

In [ ]:
### Class Imbalance

###target Variable - Count- > What is the ratio of this

In [ ]:
#### multivariate Analysis

### target with AMT_credit , Employee type, occupation type -> Bar plot hue - Stacked bar plot, Scatter Plots
### correlation multiple variables


plot(df, col = 'Income Type', hue = 'code_gender')



### Count the applications based on organization type

###  Distribution of goods price with contract type


# heatmap - corr()

### Which the 10 most correlated variables

## Scatter plots with annuity and credit amount

### use subplots wherever necessary

## study Education type, occupation type, Assets

### Create more columns -> Combining assets


### family Status vs credit amount

In [ ]:
### merge the previous application data to the current one for more insights

In [ ]:
### previous follow same steps -> Clean data, remove null columns, remove uncessary junk columns, fill na by logic if required, outlier analysis

In [ ]:
## Purpose of previous laon , contract status with previopsu loan

In [ ]:
### Summary - Recommendations, Trends, Insights imp for the business